- name: Install Apache Web Server on Ubuntu
  hosts: all
  become: yes

  vars:
    source_file: /etc/ansible/index.html
    dest_dir: /var/www/html/

  tasks: 

    - name: Install Apache Web Server on AWS Ubuntu
      apt:  update_cache=yes name=apache2 state=latest

    - name: Start Apache and enable it during boot
      service: name=apache2 state=started enabled=yes

    - name: Copy index.html to target server
      copy: src={{ source_file }} dest={{ dest_dir }} mode=0555  
  
  
